CyferShepard/Jellystat

- README.md
- src/pages/components/sessions/session-card.js
- src/pages/components/sessions/sessions.js
If no subtitles, display this in the sessions card.
Reduced the font size of playback details to prevent the card getting too crowded.
MINOR: Fixed readme instruction for installing npm packages
> Display the subtitle stream for a given session

- src/pages/components/sessions/session-card.js
- src/pages/components/sessions/sessions.js
Jellyfin reports playback for live tv with an end time of 00:00:00, replicating this in Jellystat.
Also add the current program name to the now playing item
Also some aesthetic changes to ensure playback counter row is always at the bottom of the card
NB: Jellyfin itself seems to have a bug where the CurrentProgram item does not update when a program ends and the next one starts. If this is fixed, instead of 00:00:00, the current program's start/end times could be used to display how far along the user is relative to those.
> fix NaN for live tv playback

- src/pages/components/sessions/session-card.jsx
- src/pages/components/statCards/ItemStatComponent.jsx
- src/pages/components/statCards/mp_music.jsx
- src/pages/components/statCards/mv_music.jsx
- src/pages/css/statCard.css
Hey @CyferShepard! Great job on JellyStats!
Here's a quick PR to fix to fix music album covers which were stretched on the home page. It is fixing both the session and stats cards.
**Before**
**After**
> Fix Stretched Music Album Covers

- backend/classes/axios.js
- package-lock.json
- package.json
Looks like Axios is not caching any DNS resolution by default. By adding the [cacheable-lookup](https://github.com/szmarczak/cacheable-lookup) lib and enabling it on the http agent, it will greatly reduce calls to DNS during sync/update operations in Jellystat.
Ran a quick test using my own DNS server to see how much DNS queries were made with and without cacheable-lookup lib.
For a full Jellyfin sync I would always reach the query cap on Pi-Hole, which is 1000 queries per hour. It would start replying errors at around 20% of the sync.
With the cacheable-lookup, I was able to run the full sync up to 100%. There were less than 50 queries to my DNS server for the whole process.
Should fix the DNS Spamming issue mentionned in #101.
> [Feature] Implement DNS Caching of HTTP Queries

- docker-compose.yml
Please allow me to use this space to say: Great job! I really like your UI and this project is really useful for me. Thanks!
This is a minor change that updates the `docker-compose.yml` file to add persistance. Embarrasingly, I did a pull and a restart which recreated my containers and blew away all the historical data. I should have thought about this when adding the configuration to my compose constellation but I am human and I make mistakes. 
Hopefully, having these configuration parameters in the example will help remind people when they are deploying using docker compose.
> Add the use of volumes to the example docker compose configuration

- Dockerfile
- README.md
- entry.sh
resolves #81 
This implements docker secrets via a shell script. The script loops over all environment variables that are prefixed with `FILE__` (such as `FILE__MYVAR`) and loads the contents of the file that variable points to into a new variable without the prefix (such as MYVAR).
Tested by:
Creating a file called `.jwt_secret` with the contents `'my-secret-jwt-key'`
Then using the following `docker-compose.yaml` performed a `docker compose up`
```yaml
version: '3'
services:
jellystat-db:
image: postgres
environment:
POSTGRES_USER: postgres
POSTGRES_PASSWORD: mypassword
jellystat:
build:
context: .
environment:
POSTGRES_USER: postgres
POSTGRES_PASSWORD: mypassword
POSTGRES_IP: jellystat-db
POSTGRES_PORT: 5432
TZ: Africa/Johannesburg
FILE__JWT_SECRET: /run/secrets/JWT_SECRET
secrets:
- …
```
> Docker Secrets

- backend/migrations/001_app_config_table.js
- backend/migrations/002_jf_activity_watchdog_table.js
- backend/migrations/003_jf_libraries_table.js
- backend/migrations/004_jf_library_items_table.js
- backend/migrations/005_jf_library_seasons_table.js
- backend/migrations/006_jf_library_episodes_table.js
- backend/migrations/007_jf_playback_activity_table.js
- backend/migrations/008_js_users_table.js
- backend/migrations/013_fs_last_user_activity_function.js
- backend/migrations/014_fs_library_stats_function.js
- backend/migrations/015_fs_most_active_user_function.js
- backend/migrations/016_fs_most_played_items_function.js
- backend/migrations/017_fs_most_popular_items_function.js
- backend/migrations/018_fs_most_used_clients_function.js
- backend/migrations/019_fs_most_viewed_libraries_function.js
- backend/migrations/020_fs_user_stats_function.js
- backend/migrations/021_fs_watch_stats_over_time_functions.js
- backend/migrations/022_fs_watch_stats_popular_days_of_week_function.js
- backend/migrations/023_fs_watch_stats_popular_hour_of_day_function,js.js
- backend/migrations/024_jf_item_info_table.js
- backend/migrations/026_fs_last_user_activity_function.js
- backend/migrations/028_jf_playback_reporting_plugin_data_table.js
- backend/migrations/030_jf_logging_table.js
Currently migrations are not working for some users. For example, a user with a dot inside his username(`media.jellystat`) will cause errors in SQL queries.
```
error: ALTER TABLE app_config OWNER TO media.jellystat; - syntax error at or near "."
```
> fix: add quotes to postgres user in migrations

- backend/create_database.js
- backend/db.js
- backend/migrations.js
Use POSTGRES_DATABASE environment if defined, otherwise fallback to default `jfstat`.
Resolves #152 
Hope that helps, thanks for the awesome project :)
> Use POSTGRES_DATABASE environment variable

- src/pages/components/sessions/session-card.jsx
This resolves a small visual problem in the Sessions summary area on the homepage, where the device icon for users streaming via the iOS Jellyfin app was not displayed correctly. The issue stemmed from the device name being labeled as ios, for which there is no matching asset icon available: https://github.com/jellyfin/jellyfin-web/tree/master/src/assets/img/devices -- see screenshot below:
Looking at Jellyfin's API Response for the `/Sessions` endpoint and filtering for a device that's streaming via iOS app, the returned value for `Client` is `Jellyfin Mobile (iOS)`, and `DeviceName` is `iPhone`, therefore this code piece checks if those values match and if so, sets the devicename to "apple" so a valid icon is fetched. Here's the outcome:
> Fix: Display apple icon correctly for iOS Devices

- Dockerfile
Installing **wget** in the docker image and adding a **HEALTHCHECK** that can be used to verify if the container is up and running.
The new packages add 2MB to the total image size (826MB to 828MB), which I think is reasonable. I also put in some basic values for the healthcheck which all look good on my end, but happy to tweak them if necessary.
> Adding healthcheck to docker image

- README.md
- backend/tasks/ActivityMonitor.js
Allows for filtering out playbacks that only execute for a second or two (like during testing, or when a new episode auto-plays). The new variable is called 'MINIMUM_SECONDS_TO_INCLUDE_PLAYBACK'.
Potential resolution for https://github.com/CyferShepard/Jellystat/issues/270.
> Adding environment variable to define the minimum number of seconds for a playback to be included

- src/pages/components/sessions/session-card.jsx
- src/pages/components/sessions/sessions.jsx
Not sure if you mind people contributing like this. I had fixed it on my branch an noticed a request was made for it.
Issue 
https://github.com/CyferShepard/Jellystat/issues/132
I based this on the SubtitleStream building and used the IsVideoDirect and IsAudioDirect flags to do this. I separated the Video and Audio into two different columns. I tried to keep the format the same as you had it. I am kind of new to Javascript (C++ is my main language) so I am not sure if the code is up to standards or not.
Thanks again!
> Split out Video and Audio into different columns.

- public/locales/en-UK/translation.json
- public/locales/fr-FR/translation.json
- public/locales/zh-CN/translation.json
- src/pages/components/sessions/session-card.jsx
- src/pages/components/sessions/sessions.jsx
Sorry to keep hitting you with merge requests.
I noticed when playing audio the sessions card could be updated.
Stable branch card
I modified it to look like the video line with bitrate.
I also added Artist above the song title (I could remove this if it was a decision to leave this off)
I didn't realize there was a translation table on my last merge request and had some hardcoded strings that I put in the table. I was not sure if a script ran to fill in the translations for other languages or if I needed to do that.
> Clean up audio session card & Add translations for sessions

- src/pages/components/activity/stream_info.jsx
Not sure if there is a better way of doing this. 
Problem: 
NaN gets displayed for audio only streams since it ends up doing a parseFloat on a '-' character
After Fix:
> Fix NaN showing up for audio only activity

- backend/migrations/092_fix_function_fs_get_user_activity_interrupt_groups_properly.js
- src/pages/activity_time_line.jsx
- src/pages/components/activity-timeline/activity-timeline-item.jsx
- src/pages/components/activity-timeline/helpers.jsx
- src/pages/css/timeline/activity-timeline.css
Hi, some fixes for stuff I noticed when playing with the "full release" of the activity timeline feature.
https://github.com/CyferShepard/Jellystat/commit/18926977a8be2459e47d384b7a6f50546e128040
The EpisodeCount did not get summed if multiple seasons of a show get grouped.
Before: 
After:
https://github.com/CyferShepard/Jellystat/commit/6c49ef8fc33b969d532fd847fe967ff9008534a1
If a user opens the activity timeline for the first time no libraries are selected. I think this is confusing and thus added a default fallback.
https://github.com/CyferShepard/Jellystat/commit/04ae6de8863dc1f00cd1d7fbe2d19edb310525d5
Another change to this already way to complicated function. Before the intenal grouping identifier would be calculated only on the date (to allow for the 1-month rewatch interval). …
> Activity timeline fixes and improvements

- README.md
- public/locales/ca-ES/translation.json
- public/locales/en-UK/translation.json
- public/locales/fr-FR/translation.json
- public/locales/it-IT/translation.json
- public/locales/zh-CN/translation.json
- src/pages/components/statCards/playback_method_stats.jsx
Emby has another stream type of Direct Stream. Added this to the types. I also added the IS_EMBY_API to the readme. Not sure if you wanted this or not.
Transcode is the default so it would show up twice.
Old
Update
> Emby Stream Type Fix and added IS_EMBY_API to README

- public/locales/en-UK/translation.json
- src/pages/components/activity-timeline/activity-timeline-item.jsx
One more small fix I noticed. 
Add plurality to the "Episodes" Text in the timeline.
> Add plural to timeline episode count

- README.md
- backend/server.js
This PR allows configuring the LISTEN_IP value, making it possible to bind the server to an IPv6-compatible address (e.g., ::). To maintain backward compatibility, the default remains 0.0.0.0.
> allow configuring LISTEN_IP/enable IPv6 support

- backend/routes/stats.js
- backend/swagger.json
- src/pages/components/statistics/daily-play-count.jsx
- src/pages/components/statistics/play-stats-by-day.jsx
- src/pages/components/statistics/play-stats-by-hour.jsx
`POST` is usually indicates that data is being inserted or updated, but that's not the case here.
This is a very minor change and doesn't seem to break anything.
> refactor: Use GET in `/statistics` API endpoints instead of POST

- backend/routes/stats.js
- backend/swagger.json
Implements https://github.com/CyferShepard/Jellystat/discussions/377
> feat: API endpoint `/stats/getViewsByLibraryType`
